#!/bin/bash 

#
# Wrapper script to run the debian package build of the zfsonlinux
# package
#

pushd spl
./autogen.sh
./configure
make deb-utils deb-kmod
for i in `ls *.deb`; do  dpkg -i $i; done

popd

pushd zfs
./autogen.sh
./configure
make deb-utils deb-kmod
popd

rm -rf debs
mkdir debs

cp -f spl/*.deb debs/
cp zfs/*.deb debs/

exit $?

