#!/bin/bash -f

#
# Wrapper script to run the debian package build of the zfsonlinux
# package
#

docker_image="stash.robinsystems.com:5000/bld-host:r7"
package="zfs-on-linux"
baseVersion="0.6.3"
label=".robin"
user=`id -u`

#
# Now switch to the docker image and build
#

docker run --rm -v $PWD:$PWD -w $PWD -u $user $docker_image $PWD/buildDebs -b

exit $?
