#!/bin/bash -f

#
# Wrapper script to run the debian package build of the zfsonlinux
# package
#

RELEASE_NUM=0
DEBUG_OPT="None"
if [ $# -ge 2 ]
then
	RELEASE_NUM=$1
	DEBUG_OPT=$2
elif [ $# -eq 1 ]
then
	RELEASE_NUM=$1
fi

echo $RELEASE_NUM $DEBUG_OPT
docker_image="stash.robinsystems.com:5000/bld-host:r13"
package="zfs-on-linux"
baseVersion="0.6.3"
label=".robin"
#
# Now switch to the docker image and build
#
docker run --rm -v $PWD:$PWD -w $PWD $docker_image $PWD/buildDebs ${RELEASE_NUM} ${DEBUG_OPT} -b

exit $?
